# 0: PyTorch Fundamentals

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0


## Introduction to Tensors

In [2]:
#Scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#Tensor to Python Int
scalar.item()

7

In [4]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX[1]

tensor([ 9, 10])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8 ,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors
Neural networks usually start with random tensors and we adjust according to data

In [29]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4577, 0.3049, 0.8588, 0.4099],
        [0.4534, 0.1077, 0.0414, 0.7992],
        [0.6114, 0.3651, 0.6514, 0.5954]])

In [21]:
random_tensor.ndim

4

In [23]:
#Create a tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(3, 224, 224) #Height, Width, and Color Channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and Ones

In [30]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

### Create a Range of Tensors

In [39]:
one_to_ten = torch.arange(0, 11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
torch.arange(start = 0, end = 1000, step = 77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [42]:
#Creating a tensor-like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [59]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float32, #What data type
                               device = 'mps', #mps for gpu, cpu for cpu
                               requires_grad = False) #If true, PyTorch keeps a history of every operation done to the tensor
                                #Tracks gradients if true
float_32_tensor

tensor([3., 6., 9.], device='mps:0')

In [60]:
float_32_tensor.dtype

torch.float32

In [61]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [63]:
float_16_tensor.dtype

torch.float16

In [64]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='mps:0')

In [65]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [68]:
int_32_tensor = torch.tensor([3, 6, 9], 
                             dtype = torch.int32,
                             device = 'mps')

In [69]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], device='mps:0')

### Getting Information from Tensors

In [72]:
some_tensor = torch.rand((3, 4), device = 'mps')
some_tensor

tensor([[0.2751, 0.6323, 0.6914, 0.0012],
        [0.7894, 0.7815, 0.2661, 0.7055],
        [0.3676, 0.6583, 0.2217, 0.5779]], device='mps:0')

In [73]:
print(some_tensor)
some_tensor.dtype, some_tensor.shape, some_tensor.device

tensor([[0.2751, 0.6323, 0.6914, 0.0012],
        [0.7894, 0.7815, 0.2661, 0.7055],
        [0.3676, 0.6583, 0.2217, 0.5779]], device='mps:0')


(torch.float32, torch.Size([3, 4]), device(type='mps', index=0))

### Manipulating Tensors (tensor operations)

Addition, Subtraction, Multiplication (element-wise), Division, Matrix Multiplication

In [76]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [77]:
tensor * 10

tensor([10, 20, 30])

In [78]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

In [79]:
tensor - 1

tensor([0, 1, 2])

In [80]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two ways to multiply a matrix
1. Element-Wise Multiplication
2. Matrix Multiplication (Dot Product)

There are 2 rules for matrix multiplication to work
1. The **inner dimensions** must match
(n, m) @ (m, p)
2. The resulting matrix has the shape of the **outer dimensions**
(n, m) @ (m, p) -> (n, p)

In [83]:
#ELement Wise
print(tensor, '*', tensor)
print(F"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [87]:
#Matrix Multiplication
torch.matmul(tensor, tensor)
#This example is a dot product because both tensors are 1 dimension

tensor(14)

In [88]:
tensor @ tensor

tensor(14)

In [89]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.0437, 0.1629, 0.3633],
        [0.2789, 0.4073, 0.6822],
        [0.1314, 0.1766, 0.2819]])

In [90]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.5492, 0.9532],
        [0.5425, 0.9244]])

In [93]:
tensor_A = torch.tensor([[1, 2], # 3x2 Tensor
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[2, 3], #3x2 Tensor
                         [5, 6],
                         [7, 8]]) 

In [ ]:
tensor_A.shape, tensor_B.shape #These 2 cannot be multiplied but we can transpose one of them

(torch.Size([3, 2]), torch.Size([3, 2]))

In [95]:
tensor_B.T

tensor([[2, 5, 7],
        [3, 6, 8]])

In [96]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 8, 17, 23],
        [18, 39, 53],
        [28, 61, 83]])

### Tensor Aggregation (min, max, mean, sum)

In [103]:
x = torch.arange(0, 100, 10)

In [106]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [107]:
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [111]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [114]:
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

### Postitional Min and Max
argmin() and argmax() return the position of the min and max values

In [115]:
x.argmin()

tensor(0)

In [116]:
x.argmax()

tensor(9)

In [117]:
x[0], x[9]

(tensor(0), tensor(90))

### Reshaping, Stacking, Squeezing, and Unsqueezing Tensors

* Reshaping: reshapes an input tensor to a defined shape
* View: returns a view of input tensor of certain shape but shares the same memory as original
* Stacking: combining multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze: removes all 1 dimensions from a tensor
* Unsqueeze: add a 1 dimension to a tensor
* Permute: Return a view of the input with dimensions permuted

In [124]:
import torch
x = torch.arange(1., 10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [125]:
#Adding an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [127]:
#Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [130]:
#Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [133]:
x_squeeze = torch.squeeze(x_reshaped)
x_squeeze, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [139]:
x_unsqueeze = torch.unsqueeze(x_squeeze, dim = 0)
x_unsqueeze, x_unsqueeze.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [142]:
#.permute reorders the dimension values
x_original = torch.rand((224, 224, 3))
x_permuted = x_original.permute(2, 0, 1) #Shifts the dimensions
x_permuted.shape

torch.Size([3, 224, 224])

### Selecting Data from Tensors (Indexing)

In [146]:
import torch
x = torch.arange(1, 10).reshape(1, 3 ,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [150]:
x[0][0]

tensor([1, 2, 3])

In [151]:
x[0][0][0]

tensor(1)

In [158]:
#Use : to get all of a target dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [159]:
#Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [161]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [163]:
#Return 9
x[0][2][2]

tensor(9)

In [164]:
#Return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

### PyTorch Tensors and NumPy
* Data in NumPy to PyTorch Tensor -> torch.from_numpy(nd_array)
* PyTorch Tensor to NumPy Array -> torch.Tensor.numpy()

In [174]:
import numpy as np
import torch

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [176]:
tensor = torch.ones(7)
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [177]:
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproduducability 
Reduce the randomness in neural networks and PyTorch by using a **random seed**

In [238]:
import torch
#2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8641, 0.1381, 0.4006, 0.0437],
        [0.9750, 0.9196, 0.3343, 0.5451],
        [0.0124, 0.1585, 0.3219, 0.7869]])
tensor([[0.2863, 0.3121, 0.5746, 0.2729],
        [0.1817, 0.1977, 0.4985, 0.4446],
        [0.5536, 0.4900, 0.1403, 0.8756]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [240]:
#Make random but reproducible tensors
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running Tensors on GPUs

In [2]:
import torch
print(torch.backends.mps.is_built())

True


In [3]:
device = 'mps' if torch.backends.mps.is_built() else 'cpu'

In [8]:
#Running on a gpu
tensor = torch.tensor([1, 2, 3], device = device)
tensor, tensor.device

(tensor([1, 2, 3], device='mps:0'), device(type='mps', index=0))

In [10]:
#Moving tensor back to the cpu (You can't transform back to numpy array if its on gpu)
tensor_back_to_cpu = tensor.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])

### Exercises

In [13]:
#1
rand_tensor_A = torch.rand(size = (7, 7))
rand_tensor_A

tensor([[0.9925, 0.8890, 0.5573, 0.1888, 0.6205, 0.3684, 0.4692],
        [0.3069, 0.7134, 0.2967, 0.2607, 0.5110, 0.8203, 0.7729],
        [0.1574, 0.2833, 0.4308, 0.0247, 0.3944, 0.4059, 0.6153],
        [0.9163, 0.6649, 0.3476, 0.4202, 0.8949, 0.7149, 0.4921],
        [0.9993, 0.7706, 0.7619, 0.3720, 0.8399, 0.4429, 0.0222],
        [0.7793, 0.0802, 0.2224, 0.1718, 0.3200, 0.1673, 0.4809],
        [0.8247, 0.7931, 0.9594, 0.7407, 0.7733, 0.8647, 0.0257]])

In [ ]:
#2
rand_tensor_B = torch.rand(size = (1, 7))
rand_tensor_A @ rand_tensor_B.T

tensor([[1.2609],
        [0.8750],
        [0.5983],
        [1.3840],
        [1.4310],
        [0.7471],
        [1.4947]])

In [ ]:
#3,4
torch.manual_seed(42)
rand_tensor_A = torch.rand(size = (7, 7))
torch.manual_seed(42)
rand_tensor_B = torch.rand(size = (1, 7))

rand_tensor_A @ rand_tensor_B.T

tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])

In [35]:
#5
torch.manual_seed(42)
rand_tensor_A = torch.rand(size = (7, 7), device = 'mps')
torch.manual_seed(42)
rand_tensor_B = torch.rand(size = (1, 7), device = 'mps')

rand_tensor_A @ rand_tensor_B.T

tensor([[2.6955],
        [1.4405],
        [2.5316],
        [2.6281],
        [2.2087],
        [2.4064],
        [2.2540]], device='mps:0')

In [43]:
#6
torch.manual_seed(1234)
rand_tensor_C, rand_tensor_D = torch.rand(size = (2, 3), device = 'cpu'), torch.rand(size = (2, 3), device = 'cpu')
rand_tensor_C.to('mps'), rand_tensor_D.to('mps')

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))

In [46]:
#7
matmul_A = rand_tensor_C @ rand_tensor_D.T
matmul_A

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [47]:
#8
matmul_A.max(), matmul_A.min()

(tensor(0.5617), tensor(0.3647))

In [48]:
#9
matmul_A.argmax(), matmul_A.argmin()

(tensor(3), tensor(0))

In [53]:
#10
torch.manual_seed(7)
random = torch.rand(size = (1, 1, 1, 10))
random, random.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [57]:
squeeze = torch.squeeze(random)
squeeze, squeeze.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))